#!/usr/bin/env bash

export centre=NCAR
export model=CESM2-WACCM
export var=zg
export forcing=1
export grid=gn
export mean=Amon
export initialisation=1
export physics=1

export outfile=available-files-${centre}-${model}-${var}-i${initialisation}p${physics}f${forcing}

rm $outfile 

for realisation in {1..19}; do for ssp in 126 245 370 585; do for file in $(globus ls ${globus_llnl}:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp$ssp/r${realisation}i${initialisation}p${physics}f${forcing}/${mean}/${var}/${grid}/latest/);do echo -ne "/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp$ssp/r${realisation}i${initialisation}p${physics}f${forcing}/${mean}/${var}/${grid}/latest/$file $PWD/$file\n" >> $outfile; done; done; done

#do batch transfer with... 
#globus transfer $globus_llnl $globus_nesi --batch  ./available-files-MOHC-UKESM1-0-LL-zg


