#!/usr/bin/env bash

#globus endpoint activate --web ee3aa1a0-7e4c-11e6-afc4-22000b92c261

export centre=MOHC
export model=UKESM1-0-LL
export var=zg

mkdir -p ${centre}-${model}-${var}


#for ssp in 126 245 370 585 ; do echo    /esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp${ssp}; globus ls  $globus_llnl:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp${ssp}/; done

#for realisation in {1..19}; do for ssp in 126 245 370 585  ; do for file in $(globus ls $globus_llnl:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp${ssp}/r${realisation}i1p1f2/Amon/${var}/gn/latest/); do echo $file; done; done ;done
    
#    > ./available-files-${centre}-${model}-${var}; done ; done;done

for realisation in {1..19}
do for ssp in 126 245 370 585
do for file in $(globus ls $globus_llnl:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp${ssp}/r${realisation}i1p1f2/Amon/${var}/gn/latest/)
do echo $file #>> $PWD/${centre}-${model}-${var}/available-files-${centre}-${model}-${var}
    #globus transfer $globus_llnl:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp${ssp}/r${realisation}i1p1f2/Amon/${var}/gn/latest/$file $globus_nesi:$PWD/${centre}-${model}-${var}/$file
done
done
done


