#!/usr/bin/env bash

. ~/.profile

export user=$1
export suite=$2
export stream=$3

echo $suite
echo $user

cd /home/$user/cylc-run/$suite/share/data/History_Data/

echo 'I am now here ->' $PWD

rm in.txt ; for file in *a.${stream}*.pp; do echo $file ;  echo -ne "$file $file\n" >> in.txt ; done

export destination=/gws/nopw/j04/aerchemmip_vol1/data/$suite/$stream/

globus transfer $globus_maui:/home/$user/cylc-run/$suite/share/data/History_Data/ $globus_jasmin:$destination --batch --label "CLI batch all ${stream} ${suite}" < ./in.txt


