#!/usr/bin/env bash

export centre=MOHC
export model=UKESM1-0-LL
export var=ta

rm available-files-${centre}-${model}-${var}

#for forcing in 2 ;do for realisation in {1..19}; do for ssp in 126 245 370 585; do for file in $(globus ls ${globus_llnl}:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp$ssp/r${realisation}i1p1f${forcing}/Amon/${var}/gn/latest/); do echo $file ; done; done; done; done



for forcing in 2 ;do for realisation in {1..19}; do for ssp in 126 245 370 585; do for file in $(globus ls ${globus_llnl}:/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp$ssp/r${realisation}i1p1f${forcing}/Amon/${var}/gn/latest/);do echo -ne "/esg_cmip6/CMIP6/ScenarioMIP/${centre}/${model}/ssp$ssp/r${realisation}i1p1f${forcing}/Amon/${var}/gn/latest/$file $PWD/$file\n" available-files-${centre}-${model}-${var}; done; done; done; done
