#!/usr/bin/env bash 

cd /Users/Jonny/Library/Mobile\ Documents/com\~apple\~CloudDocs/

for f in *\ *; do mv "$f" "${f// /_}"; done

for file in * ; do  export date=$(date +%Y%m%d%H%M%S) ;  rsync -vLP --remove-source-files $file /Volumes/Data/Pictures/${date}-$file ; done 

