#!/usr/bin/env bash


#####################
# Script to prepare # 
# NZESM runs for    #
# the nearline      #
# archive.          #
#                   #
# Started 20200517  #
#                   #
#####################

. ~/.profile

export suite=$1

# Tar up the fcm_make_* dirs in the cylc-run share dir.

cd ~/cylc-run/$suite/share

for thing in drivers ocean pp um
    do tar --remove-files -cvf fcm_make_${thing}.tar fcm_make_${thing}
    done





    export nprocs=foo ; export mysuite=ab123 ; for suite in $mysuite 1_$mysuite ; do  for trc in restart restart_trc; do   for icebergs in  _icebergs_ _ ; do  for month in 01 02 03 04 05 06 07 08 09 10 11 12; do for year in {1850..2200} ;  do rebuild_nemo -t 40 ${suite}o${icebergs}${year}${month}01_${trc} $nprocs &&  rm ${suite}o${icebergs}${year}${month}01_${trc}_????.nc  ; done ; done  ; done ; done ;done
