#!/bin/bash

. ~/.profile

echo 'the date is ...'
date

export project=niwa00013

for suite in u-ck290

    do

        cd ~/roses/afterburner/$suite
        set-hpc-project
        FILE=~/cylc-run/$suite/.service/contact

        if [  -f "$FILE" ]; then
                echo "$FILE exists and so " $suite "is already running!"
        fi

        if [ ! -f "$FILE" ]; then
                echo "$FILE doesn't exist, running monitoring suite " $SUITE
                rose suite-run --no-gcontrol --host=w-cylc02
        fi

    done
