#!/bin/bash

. ~/.profile

echo 'the date is ...'
date


for suite in  u-bu205

    do

    mkdir -p /nesi/project/nesi00442/$USER/afterburner/caches/streamsplit/${suite}/apy/


        cd ~/roses/afterburner/$suite
        set-hpc-project
        FILE=~/cylc-run/$suite/.service/contact

        if [  -f "$FILE" ]; then
                echo "$FILE exists and so " $suite "is already running!"
        fi

        if [ ! -f "$FILE" ]; then
                echo "$FILE doesn't exist, running monitoring suite " $SUITE
                rose suite-run --no-gcontrol --host=w-cylc02
        fi

    done
