#!/usr/bin/env bash
# this is a script to see where a run has got to...

export suiteid=$1

cd ~/cylc-run/$suiteid/work

latest_cycle_point=$(ls -td ./* | head -1)

for dir in $latest_cycle_point/{atmos*,coupled*}

do

if [ -d "$dir/pe_output" ]; then
    echo '---------------------------------'
    echo  $(basename "$dir")
      # Control will enter here if $DIRECTORY exists.
    grep -srh 'Atm_Step: Timestep' $dir/pe_output/*|tail -1
fi

done
