#! /bin/bash

module load NCO

MetO_file="/nesi/nobackup/niwa00013/williamsjh/cylc-run/u-bd889/share/data/History_Data/CICEhist/sea_ice_assess/header/aw310/*.nc"

    rm header/*.nc
for file in *.nc ; do 


    echo $file

    # loop over the only "coordinates" instances in MetO file
    #
    for coords in "TLON TLAT time" "ULON ULAT time" "TLON TLAT NCAT time"; do 
    #for coords in {0..2}; do 


   #     echo $coords
   #     if [ $coords -eq 0 ]
   #     then
   #         coords
   #         mycoords="TLON TLAT time"
   #     fi

       #
       # identify variables with those coordinates
       varList=$( ncdump -h ${MetO_file} |  grep ":coordinates" | grep "${coords}" | cut -d ":" -f 1 )


           counter=0
       #
       # loop over variables and hard-wire coordinates attribute using ncatted
       for var in ${varList} ; do
           echo $counter
           echo $var
           echo $file
          #f [[ "$counter" == 0 ]] ; then
           #   ncatted  -a coordinates,${var},o,c,"$coords" $file header/$file
          #else
              ncatted -O -a coordinates,${var},o,c,"$coords" $file 
          #fi
          let counter++
       done

    done

done
